"""
This type stub file was generated by pyright.
"""

import warnings
from . import version
from .search import Search
from .lookup import Lookup
from .ticker import Ticker
from .calendars import Calendars
from .tickers import Tickers
from .multi import download
from .live import AsyncWebSocket, WebSocket
from .utils import enable_debug_mode
from .cache import set_tz_cache_location
from .domain.sector import Sector
from .domain.industry import Industry
from .domain.market import Market, MarketRegion
from .config import YfConfig as config
from .data import Auth
from .screener.query import ETFQuery, EquityQuery, FundQuery
from .screener.screener import PREDEFINED_SCREENER_QUERIES, screen

__version__ = ...
__author__ = ...
__all__ = ['download', 'Market', 'MarketRegion', 'Search', 'Lookup', 'Ticker', 'Tickers', 'enable_debug_mode', 'set_tz_cache_location', 'Sector', 'Industry', 'WebSocket', 'AsyncWebSocket', 'Calendars', 'Auth']
__all__ += ['EquityQuery', 'FundQuery', 'ETFQuery', 'screen', 'PREDEFINED_SCREENER_QUERIES']
_NOTSET = ...
def set_config(proxy=..., retries=...): # -> None:
    ...

__all__ += ['config', 'set_config']
