"""
This type stub file was generated by pyright.
"""

"""HTTP backend abstraction.

Prefers ``curl_cffi`` for browser TLS impersonation. Falls back to plain
``requests`` with a realistic ``User-Agent`` when ``curl_cffi`` cannot be
imported (e.g. binary not buildable on the host platform — see issue #2692)
or when ``YF_DISABLE_CURL_CFFI`` is set in the environment (downstream
packagers may ship without ``curl_cffi`` even if it is installed).

The fallback is best-effort: plain ``requests`` cannot replicate the
JA3/JA4 fingerprint and HTTP/2 settings that ``curl_cffi`` provides, so
Yahoo Finance may rate-limit or block this client. ``curl_cffi`` remains
the preferred backend and the default install dependency.
"""
_DISABLE = ...
if not _DISABLE:
    _backend = ...
    HAS_CURL_CFFI = ...
else:
    _backend = ...
    HAS_CURL_CFFI = ...
requests = _backend
HTTPError = _backend.exceptions.HTTPError
_FALLBACK_USER_AGENT = ...
_fallback_warned = ...
def new_session(): # -> requests.sessions.Session | curl_cffi.requests.session.Session[Response]:
    """Create a default Session for the active backend."""
    ...

def cookie_jar(session): # -> Any:
    """Return the underlying ``http.cookiejar.CookieJar`` for either backend.

    ``curl_cffi`` exposes the jar as ``session.cookies.jar``; ``requests``
    uses ``session.cookies`` directly (it subclasses ``CookieJar``).
    """
    ...

def is_supported_session(obj) -> bool:
    """True if ``obj`` is a Session from either supported backend."""
    ...

