"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Optional, Union
from . import utils
from .scrapers.funds import FundsData

_tz_info_fetch_ctr = ...
class TickerBase:
    def __init__(self, ticker, session=...) -> None:
        """
        Initialize a Yahoo Finance Ticker object.

        Args:
            ticker (str | tuple[str, str]):
                Yahoo Finance symbol (e.g. "AAPL")
                or a tuple of (symbol, MIC) e.g. ('OR','XPAR')
                (MIC = market identifier code)

            session (requests.Session, optional):
                Custom requests session.
        """
        ...
    
    @utils.log_indent_decorator
    def history(self, *args, **kwargs) -> pd.DataFrame:
        ...
    
    def get_recommendations(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Returns a DataFrame with the recommendations
        Columns: period  strongBuy  buy  hold  sell  strongSell
        """
        ...
    
    def get_recommendations_summary(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        ...
    
    def get_upgrades_downgrades(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Returns a DataFrame with the recommendations changes (upgrades/downgrades)
        Index: date of grade
        Columns: firm toGrade fromGrade action
        """
        ...
    
    def get_calendar(self) -> dict:
        ...
    
    def get_sec_filings(self) -> dict:
        ...
    
    def get_major_holders(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        ...
    
    def get_institutional_holders(self, as_dict=...): # -> dict[Any, Any] | DataFrame | None:
        ...
    
    def get_mutualfund_holders(self, as_dict=...): # -> dict[Any, Any] | DataFrame | None:
        ...
    
    def get_insider_purchases(self, as_dict=...): # -> dict[Any, Any] | DataFrame | None:
        ...
    
    def get_insider_transactions(self, as_dict=...): # -> dict[Any, Any] | DataFrame | None:
        ...
    
    def get_insider_roster_holders(self, as_dict=...): # -> dict[Any, Any] | DataFrame | None:
        ...
    
    def get_info(self) -> dict:
        ...
    
    def get_fast_info(self): # -> FastInfo:
        ...
    
    def get_valuation_measures(self, freq=..., periods=...) -> pd.DataFrame:
        """Valuation measures (market cap, P/E, P/S, P/B, EV/EBITDA, ...).

        Returns a DataFrame with the 9 valuation measures as rows and a
        ``Current`` column plus period-end date columns (newest first). Values
        are raw numeric measures (floats, with ``NaN`` for missing cells); the
        date column labels remain ``"M/D/YYYY"`` strings.

        Args:
            freq: period columns to return — "quarterly" (default), "monthly",
                "yearly" or "trailing". The "Current" column always reflects the
                latest trailing value.
            periods: cap on the number of period (date) columns returned, newest
                first. An int >= 0 or None. The default of 5 matches the column
                count the old key-statistics page showed; ``periods=0`` returns
                only the "Current" column; ``None`` returns all available history.
                The ``valuation`` property uses this default — call the method
                form to control ``periods``.
        """
        ...
    
    def get_sustainability(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        ...
    
    def get_analyst_price_targets(self) -> dict:
        """
        Keys:   current  low  high  mean  median
        """
        ...
    
    def get_earnings_estimate(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Index:      0q  +1q  0y  +1y
        Columns:    numberOfAnalysts  avg  low  high  yearAgoEps  growth
        """
        ...
    
    def get_revenue_estimate(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Index:      0q  +1q  0y  +1y
        Columns:    numberOfAnalysts  avg  low  high  yearAgoRevenue  growth
        """
        ...
    
    def get_earnings_history(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Index:      pd.DatetimeIndex
        Columns:    epsEstimate  epsActual  epsDifference  surprisePercent
        """
        ...
    
    def get_eps_trend(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Index:      0q  +1q  0y  +1y
        Columns:    current  7daysAgo  30daysAgo  60daysAgo  90daysAgo
        """
        ...
    
    def get_eps_revisions(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Index:      0q  +1q  0y  +1y
        Columns:    upLast7days  upLast30days  downLast7days  downLast30days
        """
        ...
    
    def get_growth_estimates(self, as_dict=...): # -> dict[Any, Any] | DataFrame:
        """
        Index:      0q  +1q  0y  +1y +5y -5y
        Columns:    stock  industry  sector  index
        """
        ...
    
    def get_earnings(self, as_dict=..., freq=...): # -> None:
        """
        :Parameters:
            as_dict: bool
                Return table as Python dict
                Default is False
            freq: str
                "yearly" or "quarterly" or "trailing"
                Default is "yearly"
        """
        ...
    
    def get_income_stmt(self, as_dict=..., pretty=..., freq=...): # -> dict[Any, Any] | DataFrame:
        """
        :Parameters:
            as_dict: bool
                Return table as Python dict
                Default is False
            pretty: bool
                Format row names nicely for readability
                Default is False
            freq: str
                "yearly" or "quarterly" or "trailing"
                Default is "yearly"
        """
        ...
    
    def get_incomestmt(self, as_dict=..., pretty=..., freq=...): # -> dict[Any, Any] | DataFrame:
        ...
    
    def get_financials(self, as_dict=..., pretty=..., freq=...): # -> dict[Any, Any] | DataFrame:
        ...
    
    def get_balance_sheet(self, as_dict=..., pretty=..., freq=...): # -> dict[Any, Any] | DataFrame:
        """
        :Parameters:
            as_dict: bool
                Return table as Python dict
                Default is False
            pretty: bool
                Format row names nicely for readability
                Default is False
            freq: str
                "yearly" or "quarterly"
                Default is "yearly"
        """
        ...
    
    def get_balancesheet(self, as_dict=..., pretty=..., freq=...): # -> dict[Any, Any] | DataFrame:
        ...
    
    def get_cash_flow(self, as_dict=..., pretty=..., freq=...) -> Union[pd.DataFrame, dict]:
        """
        :Parameters:
            as_dict: bool
                Return table as Python dict
                Default is False
            pretty: bool
                Format row names nicely for readability
                Default is False
            freq: str
                "yearly" or "quarterly"
                Default is "yearly"
        """
        ...
    
    def get_cashflow(self, as_dict=..., pretty=..., freq=...): # -> DataFrame | dict[Any, Any]:
        ...
    
    def get_dividends(self, period=...) -> pd.Series:
        ...
    
    def get_capital_gains(self, period=...) -> pd.Series:
        ...
    
    def get_splits(self, period=...) -> pd.Series:
        ...
    
    def get_actions(self, period=...) -> pd.Series:
        ...
    
    def get_shares(self, as_dict=...) -> Union[pd.DataFrame, dict]:
        ...
    
    @utils.log_indent_decorator
    def get_shares_full(self, start=..., end=...): # -> Series | None:
        ...
    
    def get_isin(self) -> Optional[str]:
        ...
    
    def get_news(self, count=..., tab=...) -> list:
        """Allowed options for tab: "news", "all", "press releases"""
        ...
    
    def get_earnings_dates(self, limit=..., offset=...) -> Optional[pd.DataFrame]:
        ...
    
    def get_history_metadata(self, repair=...) -> dict:
        """
        repair default value depends on whether user requested price repair
        with previous history() call. If user did not set repair here, then
        it is set to match previous history() call.
        """
        ...
    
    def get_funds_data(self) -> Optional[FundsData]:
        ...
    
    def live(self, message_handler=..., verbose=...): # -> None:
        ...
    


