"""
This type stub file was generated by pyright.
"""

import peewee as _peewee

_cache_init_lock = ...
class _TzCacheException(Exception):
    ...


class _TzCacheDummy:
    """Dummy cache to use if tz cache is disabled"""
    def lookup(self, tkr): # -> None:
        ...
    
    def store(self, tkr, tz): # -> None:
        ...
    
    @property
    def tz_db(self): # -> None:
        ...
    


class _TzCacheManager:
    _tz_cache = ...
    @classmethod
    def get_tz_cache(cls): # -> _TzCache | None:
        ...
    


class _TzDBManager:
    _db = ...
    _cache_dir = ...
    @classmethod
    def get_database(cls): # -> SqliteDatabase | None:
        ...
    
    @classmethod
    def close_db(cls): # -> None:
        ...
    
    @classmethod
    def set_location(cls, new_cache_dir): # -> None:
        ...
    
    @classmethod
    def get_location(cls): # -> str:
        ...
    


tz_db_proxy = ...
class _TZ_KV(_peewee.Model):
    key = ...
    value = ...
    class Meta:
        database = ...
        without_rowid = ...
    
    


class _TzCache:
    def __init__(self) -> None:
        ...
    
    def get_db(self): # -> SqliteDatabase | None:
        ...
    
    def initialise(self): # -> None:
        ...
    
    def lookup(self, key): # -> str | None:
        ...
    
    def store(self, key, value): # -> None:
        ...
    


def get_tz_cache(): # -> _TzCache | None:
    ...

class _CookieCacheException(Exception):
    ...


class _CookieCacheDummy:
    """Dummy cache to use if Cookie cache is disabled"""
    def lookup(self, tkr): # -> None:
        ...
    
    def store(self, tkr, Cookie): # -> None:
        ...
    
    @property
    def Cookie_db(self): # -> None:
        ...
    


class _CookieCacheManager:
    _Cookie_cache = ...
    @classmethod
    def get_cookie_cache(cls): # -> _CookieCache | None:
        ...
    


class _CookieDBManager:
    _db = ...
    _cache_dir = ...
    @classmethod
    def get_database(cls): # -> SqliteDatabase | None:
        ...
    
    @classmethod
    def close_db(cls): # -> None:
        ...
    
    @classmethod
    def set_location(cls, new_cache_dir): # -> None:
        ...
    
    @classmethod
    def get_location(cls): # -> str:
        ...
    


Cookie_db_proxy = ...
class ISODateTimeField(_peewee.DateTimeField):
    def db_value(self, value): # -> str:
        ...
    
    def python_value(self, value): # -> datetime:
        ...
    


class _CookieSchema(_peewee.Model):
    strategy = ...
    fetch_date = ...
    cookie_bytes = ...
    class Meta:
        database = ...
        without_rowid = ...
    
    


class _CookieCache:
    def __init__(self) -> None:
        ...
    
    def get_db(self): # -> SqliteDatabase | None:
        ...
    
    def initialise(self): # -> None:
        ...
    
    def lookup(self, strategy): # -> dict[str, Any] | None:
        ...
    
    def store(self, strategy, cookie): # -> None:
        ...
    


def get_cookie_cache(): # -> _CookieCache | None:
    ...

class _ISINCacheException(Exception):
    ...


class _ISINCacheDummy:
    """Dummy cache to use if isin cache is disabled"""
    def lookup(self, isin): # -> None:
        ...
    
    def store(self, isin, tkr): # -> None:
        ...
    
    @property
    def tz_db(self): # -> None:
        ...
    


class _ISINCacheManager:
    _isin_cache = ...
    @classmethod
    def get_isin_cache(cls): # -> _ISINCache | None:
        ...
    


class _ISINDBManager:
    _db = ...
    _cache_dir = ...
    @classmethod
    def get_database(cls): # -> SqliteDatabase | None:
        ...
    
    @classmethod
    def close_db(cls): # -> None:
        ...
    
    @classmethod
    def set_location(cls, new_cache_dir): # -> None:
        ...
    
    @classmethod
    def get_location(cls): # -> str:
        ...
    


isin_db_proxy = ...
class _ISIN_KV(_peewee.Model):
    key = ...
    value = ...
    created_at = ...
    class Meta:
        database = ...
        without_rowid = ...
    
    


class _ISINCache:
    def __init__(self) -> None:
        ...
    
    def get_db(self): # -> SqliteDatabase | None:
        ...
    
    def initialise(self): # -> None:
        ...
    
    def lookup(self, key): # -> str | None:
        ...
    
    def store(self, key, value): # -> None:
        ...
    


def get_isin_cache(): # -> _ISINCache | None:
    ...

def set_cache_location(cache_dir: str): # -> None:
    """
    Sets the path to create the "py-yfinance" cache folder in.
    Useful if the default folder returned by "appdir.user_cache_dir()" is not writable.
    Must be called before cache is used (that is, before fetching tickers).
    :param cache_dir: Path to use for caches
    :return: None
    """
    ...

def set_tz_cache_location(cache_dir: str): # -> None:
    ...

