"""
This type stub file was generated by pyright.
"""

class NestedConfig:
    def __init__(self, name, data) -> None:
        ...
    
    def __getattr__(self, key):
        ...
    
    def __setattr__(self, key, value): # -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class ConfigMgr:
    def __init__(self) -> None:
        ...
    
    def __getattr__(self, key): # -> NestedConfig:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


YfConfig = ...
