"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from . import utils

cache_maxsize = ...
def lru_cache_freezeargs(func): # -> _Wrapped:
    """
    Decorator transforms mutable dictionary and list arguments into immutable types
    Needed so lru_cache can cache method calls what has dict or list arguments.
    """
    ...

class SingletonMeta(type):
    """
    Metaclass that creates a Singleton instance.
    """
    _instances = ...
    _lock = ...
    def __call__(cls, *args, **kwargs):
        ...
    


class YfData(metaclass=SingletonMeta):
    """
    Have one place to retrieve data from Yahoo API in order to ease caching and speed up operations.
    Singleton means one session one cookie shared by all threads.
    """
    def __init__(self, session=...) -> None:
        ...
    
    def set_login_cookies(self, cookie_t, cookie_y): # -> None:
        ...
    
    @utils.log_indent_decorator
    def get(self, url, params=..., timeout=...): # -> curl_cffi.requests.models.Response | requests.models.Response:
        ...
    
    @utils.log_indent_decorator
    def post(self, url, body=..., params=..., timeout=..., data=...):
        ...
    
    @lru_cache_freezeargs
    @lru_cache(maxsize=cache_maxsize)
    def cache_get(self, url, params=..., timeout=...): # -> curl_cffi.requests.models.Response | requests.models.Response:
        ...
    
    def get_raw_json(self, url, params=..., timeout=...): # -> Any:
        ...
    


_SUBSCRIPTIONS_URL = ...
_TIER_NAMES = ...
class Auth:
    def __init__(self, session=...) -> None:
        ...
    
    def set_login_cookies(self, cookie_t: str, cookie_y: str) -> bool:
        """
        Set the login cookies and verify they are valid.

        How to Obtain the Cookies:
            1. Open your browser (e.g., Chrome, Firefox).
            2. Log in to Yahoo Finance (https://finance.yahoo.com).
            3. Open the browser's Developer Tools:
               Press `F12` or `Ctrl + Shift + I` (Windows/Linux) or `Cmd + Option + I` (Mac).
            4. Go to the "Application" tab (Chrome) or "Storage" tab (Firefox).
            5. In the "Cookies" section, select `https://finance.yahoo.com`.
            6. Look for the cookies named `T` and `Y`.
            7. Copy the values of these cookies and pass them to this function.

        Args:
            cookie_t (str): The value for the 'T' cookie.
            cookie_y (str): The value for the 'Y' cookie.

        Returns:
            bool: ``True`` if the cookies are valid (the account is logged in),
            ``False`` otherwise (also emitted as a warning). The cookies are
            stored regardless. ``False`` can also mean Yahoo was transiently
            unreachable, so it is not treated as a hard error.
        """
        ...
    
    def check_login(self) -> bool:
        """Check whether the user is logged in to Yahoo Finance.

        Note: ``False`` during a transient error (e.g. Yahoo briefly
        unreachable) means "could not confirm" rather than "logged out" — the
        stored login cookies are kept and remain protected in that case.
        """
        ...
    
    def subscription_tier(self) -> str | None:
        """Return the Yahoo Finance subscription tier of the logged-in account.

        Read directly from the account's tier id in ``subscriptionView`` (the
        value the account is billed against) rather than inferring it from the
        granted feature set, which Yahoo reshuffles between tiers.

        Returns:
            str | None: ``'gold'``, ``'silver'`` or ``'bronze'`` for a named
            subscription (``'premium'`` for a subscribed tier with no marketed
            name), ``'free'`` when logged in without a subscription, or ``None``
            when not logged in.
        """
        ...
    
    @property
    def user(self) -> dict | None:
        """
        Get the logged-in user's details.

        Returns:
            dict | None: ``{'guid': ...}`` if logged in, or ``None`` if not.
        """
        ...
    


