"""
This type stub file was generated by pyright.
"""

class YFException(Exception):
    def __init__(self, description=...) -> None:
        ...
    


class YFDataException(YFException):
    ...


class YFNotImplementedError(NotImplementedError):
    def __init__(self, method_name) -> None:
        ...
    


class YFTickerMissingError(YFException):
    """Expected ticker data is missing.

    By default the message speculates the ticker is delisted, because Yahoo
    rarely explains the absence. Pass possibly_delisted=False when the real
    cause is known, so the message does not mislead.
    """
    def __init__(self, ticker, rationale, possibly_delisted=...) -> None:
        ...
    


class YFTzMissingError(YFTickerMissingError):
    def __init__(self, ticker) -> None:
        ...
    


class YFPricesMissingError(YFTickerMissingError):
    """Yahoo returned no price data for the requested range/interval.

    When Yahoo states an explicit reason, pass it as yahoo_reason: that
    reason becomes the whole message and the speculative 'possibly delisted'
    prefix and generic 'no price data found' text are dropped, because Yahoo
    has already explained the absence. Otherwise the message reports the
    request context (debug_info) and keeps the delisting speculation.
    """
    def __init__(self, ticker, debug_info, yahoo_reason=...) -> None:
        ...
    


class YFEarningsDateMissing(YFTickerMissingError):
    def __init__(self, ticker) -> None:
        ...
    


class YFInvalidPeriodError(YFException):
    def __init__(self, ticker, invalid_period, valid_ranges) -> None:
        ...
    


class YFRateLimitError(YFException):
    def __init__(self) -> None:
        ...
    


