"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, Union

class BaseWebSocket:
    def __init__(self, url: str = ..., verbose=...) -> None:
        ...
    


class AsyncWebSocket(BaseWebSocket):
    """
    Asynchronous WebSocket client for streaming real time pricing data.
    """
    def __init__(self, url: str = ..., verbose=...) -> None:
        """
        Initialize the AsyncWebSocket client.

        Args:
            url (str): The WebSocket server URL. Defaults to Yahoo Finance's WebSocket URL.
            verbose (bool): Flag to enable or disable print statements. Defaults to True.
        """
        ...
    
    async def subscribe(self, symbols: Union[str, List[str]]): # -> None:
        """
        Subscribe to a stock symbol or a list of stock symbols.

        Args:
            symbols (Union[str, List[str]]): Stock symbol(s) to subscribe to.
        """
        ...
    
    async def unsubscribe(self, symbols: Union[str, List[str]]): # -> None:
        """
        Unsubscribe from a stock symbol or a list of stock symbols.

        Args:
            symbols (Union[str, List[str]]): Stock symbol(s) to unsubscribe from.
        """
        ...
    
    async def listen(self, message_handler=...):
        """
        Start listening to messages from the WebSocket server.

        Args:
            message_handler (Optional[Callable[[dict], None]]): Optional function to handle received messages.
        """
        ...
    
    async def close(self): # -> None:
        """Close the WebSocket connection."""
        ...
    
    async def __aenter__(self): # -> Self:
        ...
    
    async def __aexit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    


class WebSocket(BaseWebSocket):
    """
    Synchronous WebSocket client for streaming real time pricing data.
    """
    def __init__(self, url: str = ..., verbose=...) -> None:
        """
        Initialize the WebSocket client.

        Args:
            url (str): The WebSocket server URL. Defaults to Yahoo Finance's WebSocket URL.
            verbose (bool): Flag to enable or disable print statements. Defaults to True.
        """
        ...
    
    def subscribe(self, symbols: Union[str, List[str]]): # -> None:
        """
        Subscribe to a stock symbol or a list of stock symbols.

        Args:
            symbols (Union[str, List[str]]): Stock symbol(s) to subscribe to.
        """
        ...
    
    def unsubscribe(self, symbols: Union[str, List[str]]): # -> None:
        """
        Unsubscribe from a stock symbol or a list of stock symbols.

        Args:
            symbols (Union[str, List[str]]): Stock symbol(s) to unsubscribe from.
        """
        ...
    
    def listen(self, message_handler: Optional[Callable[[dict], None]] = ...): # -> None:
        """
        Start listening to messages from the WebSocket server.

        Args:
            message_handler (Optional[Callable[[dict], None]]): Optional function to handle received messages.
        """
        ...
    
    def close(self): # -> None:
        """Close the WebSocket connection."""
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    


