"""
This type stub file was generated by pyright.
"""

import pandas as pd

LOOKUP_TYPES = ...
class Lookup:
    """
    Fetches quote (ticker) lookups from Yahoo Finance.

    :param query: The search query for financial data lookup.
    :type query: str
    :param session: Custom HTTP session for requests (default None).
    :param timeout: Request timeout in seconds (default 30).
    :param raise_errors: Raise exceptions on error (default True).
    """
    def __init__(self, query: str, session=..., timeout=..., raise_errors=...) -> None:
        ...
    
    def get_all(self, count=...) -> pd.DataFrame:
        """
        Returns all available financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_stock(self, count=...) -> pd.DataFrame:
        """
        Returns stock related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_mutualfund(self, count=...) -> pd.DataFrame:
        """
        Returns mutual funds related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_etf(self, count=...) -> pd.DataFrame:
        """
        Returns ETFs related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_index(self, count=...) -> pd.DataFrame:
        """
        Returns Indices related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_future(self, count=...) -> pd.DataFrame:
        """
        Returns Futures related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_currency(self, count=...) -> pd.DataFrame:
        """
        Returns Currencies related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    def get_cryptocurrency(self, count=...) -> pd.DataFrame:
        """
        Returns Cryptocurrencies related financial instruments.

        :param count: The number of results to retrieve.
        :type count: int
        """
        ...
    
    @property
    def all(self) -> pd.DataFrame:
        """Returns all available financial instruments."""
        ...
    
    @property
    def stock(self) -> pd.DataFrame:
        """Returns stock related financial instruments."""
        ...
    
    @property
    def mutualfund(self) -> pd.DataFrame:
        """Returns mutual funds related financial instruments."""
        ...
    
    @property
    def etf(self) -> pd.DataFrame:
        """Returns ETFs related financial instruments."""
        ...
    
    @property
    def index(self) -> pd.DataFrame:
        """Returns Indices related financial instruments."""
        ...
    
    @property
    def future(self) -> pd.DataFrame:
        """Returns Futures related financial instruments."""
        ...
    
    @property
    def currency(self) -> pd.DataFrame:
        """Returns Currencies related financial instruments."""
        ...
    
    @property
    def cryptocurrency(self) -> pd.DataFrame:
        """Returns Cryptocurrencies related financial instruments."""
        ...
    


