"""
This type stub file was generated by pyright.
"""

import pandas as _pd
from typing import Union
from . import utils

class _DownloadCtx:
    """Per-call scratch state for download(). Concurrent calls each get
    their own instance, so no shared mutation between threads."""
    __slots__ = ...
    def __init__(self) -> None:
        ...
    


@utils.log_indent_decorator
def download(tickers, start=..., end=..., actions=..., threads=..., ignore_tz=..., group_by=..., auto_adjust=..., back_adjust=..., repair=..., keepna=..., progress=..., period=..., interval=..., prepost=..., rounding=..., timeout=..., session=..., multi_level_index=...) -> Union[_pd.DataFrame, None]:
    """
    Download yahoo tickers
    :Parameters:
        tickers : str, list
            List of tickers to download
        period : str
            Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
            Default: '1mo' if start & end None
            Either Use period parameter or use start and end
        interval : str
            Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
            Intraday data cannot extend last 60 days
            Note: 30m data is fetched from Yahoo as 15m then resampled, to work around a Yahoo API bug
        start: str
            Download start date string (YYYY-MM-DD) or _datetime, inclusive.
            Default is 99 years ago
            E.g. for start="2020-01-01", the first data point will be on "2020-01-01"
        end: str
            Download end date string (YYYY-MM-DD) or _datetime, exclusive.
            Default is now
            E.g. for end="2023-01-01", the last data point will be on "2022-12-31"
        group_by : str
            Group by 'ticker' or 'column' (default)
        prepost : bool
            Include Pre and Post market data in results?
            Default is False
        auto_adjust: bool
            Adjust all OHLC automatically? Default is True
        repair: bool
            Detect currency unit 100x mixups and attempt repair
            Default is False
        keepna: bool
            Keep NaN rows returned by Yahoo?
            Default is False
        actions: bool
            Download dividend + stock splits data. Default is False
        threads: bool / int
            How many threads to use for mass downloading. Default is True
        ignore_tz: bool
            When combining from different timezones, ignore that part of datetime.
            Default depends on interval. Intraday = False. Day+ = True.
            Also controls the returned index's timezone: if True, the index is
            tz-naive. If False (the intraday default), the index is converted
            to the most common exchange timezone among the requested tickers
            (before 1.4.0, this case always returned UTC instead; see CHANGELOG).
        rounding: bool
            Optional. Round values to 2 decimal places?
        timeout: None or float
            If not None stops waiting for a response after given number of
            seconds. (Can also be a fraction of a second e.g. 0.01)
        session: None or Session
            Optional. Pass your own session object to be used for all requests
        multi_level_index: bool
            Optional. Always return a MultiIndex DataFrame? Default is True
    """
    ...

def reindex_dfs(dfs, ignore_tz):
    ...

