"""
This type stub file was generated by pyright.
"""

class Search:
    def __init__(self, query, max_results=..., news_count=..., lists_count=..., include_cb=..., include_nav_links=..., include_research=..., include_cultural_assets=..., enable_fuzzy_query=..., recommended=..., session=..., timeout=..., raise_errors=...) -> None:
        """
        Fetches and organizes search results from Yahoo Finance, including stock quotes and news articles.

        Args:
            query: The search query (ticker symbol or company name).
            max_results: Maximum number of stock quotes to return (default 8).
            news_count: Number of news articles to include (default 8).
            lists_count: Number of lists to include (default 8).
            include_cb: Include the company breakdown (default True).
            include_nav_links: Include the navigation links (default False).
            include_research: Include the research reports (default False).
            include_cultural_assets: Include the cultural assets (default False).
            enable_fuzzy_query: Enable fuzzy search for typos (default False).
            recommended: Recommended number of results to return (default 8).
            session: Custom HTTP session for requests (default None).
            timeout: Request timeout in seconds (default 30).
            raise_errors: Raise exceptions on error (default True).
        """
        ...
    
    def search(self) -> Search:
        """Search using the query parameters defined in the constructor."""
        ...
    
    @property
    def quotes(self) -> list:
        """Get the quotes from the search results."""
        ...
    
    @property
    def news(self) -> list:
        """Get the news from the search results."""
        ...
    
    @property
    def lists(self) -> list:
        """Get the lists from the search results."""
        ...
    
    @property
    def research(self) -> list:
        """Get the research reports from the search results."""
        ...
    
    @property
    def nav(self) -> list:
        """Get the navigation links from the search results."""
        ...
    
    @property
    def all(self) -> dict[str, list]:
        """Get all the results from the search results: filtered down version of response."""
        ...
    
    @property
    def response(self) -> dict:
        """Get the raw response from the search results."""
        ...
    


