"""
This type stub file was generated by pyright.
"""

import pandas as _pd
from .base import TickerBase
from .scrapers.funds import FundsData

class Ticker(TickerBase):
    def __init__(self, ticker, session=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def option_chain(self, date=..., tz=...): # -> yfinance.ticker.Ticker.Options:
        ...
    
    @property
    def isin(self): # -> str | None:
        ...
    
    @property
    def major_holders(self) -> _pd.DataFrame:
        ...
    
    @property
    def institutional_holders(self) -> _pd.DataFrame:
        ...
    
    @property
    def mutualfund_holders(self) -> _pd.DataFrame:
        ...
    
    @property
    def insider_purchases(self) -> _pd.DataFrame:
        ...
    
    @property
    def insider_transactions(self) -> _pd.DataFrame:
        ...
    
    @property
    def insider_roster_holders(self) -> _pd.DataFrame:
        ...
    
    @property
    def dividends(self) -> _pd.Series:
        ...
    
    @property
    def capital_gains(self) -> _pd.Series:
        ...
    
    @property
    def splits(self) -> _pd.Series:
        ...
    
    @property
    def actions(self) -> _pd.DataFrame:
        ...
    
    @property
    def shares(self) -> _pd.DataFrame:
        ...
    
    @property
    def info(self) -> dict:
        ...
    
    @property
    def fast_info(self): # -> FastInfo:
        ...
    
    @property
    def valuation(self) -> _pd.DataFrame:
        ...
    
    @property
    def calendar(self) -> dict:
        """
        Returns a dictionary of events, earnings, and dividends for the ticker
        """
        ...
    
    @property
    def sec_filings(self) -> dict:
        ...
    
    @property
    def recommendations(self): # -> dict[Any, Any] | DataFrame:
        ...
    
    @property
    def recommendations_summary(self): # -> dict[Any, Any] | DataFrame:
        ...
    
    @property
    def upgrades_downgrades(self): # -> dict[Any, Any] | DataFrame:
        ...
    
    @property
    def earnings(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_earnings(self) -> _pd.DataFrame:
        ...
    
    @property
    def income_stmt(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_income_stmt(self) -> _pd.DataFrame:
        ...
    
    @property
    def ttm_income_stmt(self) -> _pd.DataFrame:
        ...
    
    @property
    def incomestmt(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_incomestmt(self) -> _pd.DataFrame:
        ...
    
    @property
    def ttm_incomestmt(self) -> _pd.DataFrame:
        ...
    
    @property
    def financials(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_financials(self) -> _pd.DataFrame:
        ...
    
    @property
    def ttm_financials(self) -> _pd.DataFrame:
        ...
    
    @property
    def balance_sheet(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_balance_sheet(self) -> _pd.DataFrame:
        ...
    
    @property
    def balancesheet(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_balancesheet(self) -> _pd.DataFrame:
        ...
    
    @property
    def cash_flow(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_cash_flow(self) -> _pd.DataFrame:
        ...
    
    @property
    def ttm_cash_flow(self) -> _pd.DataFrame:
        ...
    
    @property
    def cashflow(self) -> _pd.DataFrame:
        ...
    
    @property
    def quarterly_cashflow(self) -> _pd.DataFrame:
        ...
    
    @property
    def ttm_cashflow(self) -> _pd.DataFrame:
        ...
    
    @property
    def analyst_price_targets(self) -> dict:
        ...
    
    @property
    def earnings_estimate(self) -> _pd.DataFrame:
        ...
    
    @property
    def revenue_estimate(self) -> _pd.DataFrame:
        ...
    
    @property
    def earnings_history(self) -> _pd.DataFrame:
        ...
    
    @property
    def eps_trend(self) -> _pd.DataFrame:
        ...
    
    @property
    def eps_revisions(self) -> _pd.DataFrame:
        ...
    
    @property
    def growth_estimates(self) -> _pd.DataFrame:
        ...
    
    @property
    def sustainability(self) -> _pd.DataFrame:
        ...
    
    @property
    def options(self) -> tuple:
        ...
    
    @property
    def news(self) -> list:
        ...
    
    @property
    def earnings_dates(self) -> _pd.DataFrame:
        ...
    
    @property
    def history_metadata(self) -> dict:
        ...
    
    @property
    def funds_data(self) -> FundsData:
        ...
    


