"""
This type stub file was generated by pyright.
"""

class Tickers:
    def __repr__(self): # -> LiteralString:
        ...
    
    def __init__(self, tickers, session=...) -> None:
        ...
    
    def history(self, period=..., interval=..., start=..., end=..., prepost=..., actions=..., auto_adjust=..., repair=..., threads=..., group_by=..., progress=..., timeout=..., **kwargs): # -> DataFrame | None:
        ...
    
    def download(self, period=..., interval=..., start=..., end=..., prepost=..., actions=..., auto_adjust=..., repair=..., threads=..., group_by=..., progress=..., timeout=..., **kwargs): # -> DataFrame | None:
        ...
    
    def news(self): # -> dict[Any, list[Any]]:
        ...
    
    def live(self, message_handler=..., verbose=...): # -> None:
        ...
    


