"""
This type stub file was generated by pyright.
"""

import logging
from typing import List, Optional

def attributes(obj): # -> dict[str, Any]:
    ...

class IndentLoggerAdapter(logging.LoggerAdapter):
    def process(self, msg, kwargs): # -> tuple[LiteralString | Any, MutableMapping[str, Any]]:
        ...
    


_indentation_level = ...
class IndentationContext:
    def __init__(self, increment=...) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


def get_indented_logger(name=...): # -> IndentLoggerAdapter:
    ...

def log_indent_decorator(func): # -> _Wrapped:
    ...

class MultiLineFormatter(logging.Formatter):
    def __init__(self, fmt) -> None:
        ...
    
    def format(self, record): # -> str:
        ...
    


yf_logger = ...
yf_log_indented = ...
class YFLogFormatter(logging.Filter):
    def filter(self, record): # -> Literal[True]:
        ...
    


def get_yf_logger(): # -> IndentLoggerAdapter | Logger:
    ...

def enable_debug_mode(): # -> None:
    ...

def is_isin(string): # -> bool:
    ...

def get_all_by_isin(isin): # -> dict[str, Any]:
    ...

def get_ticker_by_isin(isin):
    ...

def get_info_by_isin(isin):
    ...

def get_news_by_isin(isin):
    ...

def empty_df(index=...): # -> DataFrame:
    ...

def empty_earnings_dates_df(): # -> DataFrame:
    ...

def build_template(data): # -> tuple[list[Any], list[Any], list[Any], list[Any]]:
    """
    build_template returns the details required to rebuild any of the yahoo finance financial statements in the same order as the yahoo finance webpage. The function is built to be used on the "FinancialTemplateStore" json which appears in any one of the three yahoo finance webpages: "/financials", "/cash-flow" and "/balance-sheet".

    Returns:
        - template_annual_order: The order that annual figures should be listed in.
        - template_ttm_order: The order that TTM (Trailing Twelve Month) figures should be listed in.
        - template_order: The order that quarterlies should be in (note that quarterlies have no pre-fix - hence why this is required).
        - level_detail: The level of each individual line item. E.g. for the "/financials" webpage, "Total Revenue" is a level 0 item and is the summation of "Operating Revenue" and "Excise Taxes" which are level 1 items.

    """
    ...

def retrieve_financial_details(data): # -> tuple[list[Any], list[Any]]:
    """
    retrieve_financial_details returns all of the available financial details under the
    "QuoteTimeSeriesStore" for any of the following three yahoo finance webpages:
    "/financials", "/cash-flow" and "/balance-sheet".

    Returns:
        - TTM_dicts: A dictionary full of all of the available Trailing Twelve Month figures, this can easily be converted to a pandas dataframe.
        - Annual_dicts: A dictionary full of all of the available Annual figures, this can easily be converted to a pandas dataframe.
    """
    ...

def format_annual_financial_statement(level_detail, annual_dicts, annual_order, ttm_dicts=..., ttm_order=...): # -> DataFrame | Series:
    """
    format_annual_financial_statement formats any annual financial statement

    Returns:
        - _statement: A fully formatted annual financial statement in pandas dataframe.
    """
    ...

def format_quarterly_financial_statement(_statement, level_detail, order):
    """
    format_quarterly_financial_statements formats any quarterly financial statement

    Returns:
        - _statement: A fully formatted quarterly financial statement in pandas dataframe.
    """
    ...

def camel2title(strings: List[str], sep: str = ..., acronyms: Optional[List[str]] = ...) -> List[str]:
    ...

def snake_case_2_camelCase(s):
    ...

def is_valid_period_format(period): # -> bool:
    """Check if the provided period has a valid format."""
    ...

def auto_adjust(data):
    ...

def back_adjust(data):
    """ back-adjusted data to mimic true historical prices """
    ...

def parse_quotes(data): # -> DataFrame:
    ...

def parse_actions(data): # -> tuple[DataFrame, DataFrame | Series | Any | Self, DataFrame]:
    ...

def set_df_tz(df, interval, tz):
    ...

def fix_Yahoo_returning_prepost_unrequested(quotes, interval, tradingPeriods):
    ...

def fix_Yahoo_returning_live_separate(quotes, interval, tz_exchange, prepost, repair=..., currency=...): # -> tuple[Any, None] | tuple[DataFrame | Any, Any | None]:
    ...

def safe_merge_dfs(df_main, df_sub, interval): # -> DataFrame:
    ...

def fix_Yahoo_dst_issue(df, interval):
    ...

def is_valid_timezone(tz: str) -> bool:
    ...

def format_history_metadata(md): # -> dict[Any, Any]:
    ...

class ProgressBar:
    def __init__(self, iterations, text=...) -> None:
        ...
    
    def completed(self): # -> None:
        ...
    
    def animate(self, iteration=...): # -> None:
        ...
    
    def update_iteration(self, val=...): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def dynamic_docstring(placeholders: dict): # -> Callable[..., Any]:
    """
    A decorator to dynamically update the docstring of a function or method.
    
    Args:
        placeholders (dict): A dictionary where keys are placeholder names and values are the strings to insert.
    """
    ...

def generate_list_table_from_dict(data: dict, bullets: bool = ..., title: str = ...) -> str:
    """
    Generate a list-table for the docstring showing permitted keys/values.
    """
    ...

def generate_list_table_from_dict_universal(data: dict, bullets: bool = ..., title: str = ..., concat_keys=...) -> str:
    """
    Generate a list-table for the docstring showing permitted keys/values.
    """
    ...

