"""
This type stub file was generated by pyright.
"""

import pandas as _pd
from typing import Optional
from .domain import Domain

class Industry(Domain):
    """
    Represents an industry within a sector.
    """
    def __init__(self, key, session=..., region: str = ...) -> None:
        """
        Args:
            key (str): The key identifier for the industry.
            session (optional): The session to use for requests.
            region (str): Yahoo region (ISO 3166-1 alpha-2 country code, e.g.
                "US", "GB", "FR", "DE", "JP"). Scopes top performing/growth
                company listings. Defaults to "US".
        """
        ...
    
    def __repr__(self): # -> str:
        """
        Returns a string representation of the Industry instance.
        
        Returns:
            str: String representation of the Industry instance.
        """
        ...
    
    @property
    def sector_key(self) -> str:
        """
        Returns the sector key of the industry.
        
        Returns:
            str: The sector key.
        """
        ...
    
    @property
    def sector_name(self) -> str:
        """
        Returns the sector name of the industry.
        
        Returns:
            str: The sector name.
        """
        ...
    
    @property
    def top_performing_companies(self) -> Optional[_pd.DataFrame]:
        """
        Returns the top performing companies in the industry.
        
        Returns:
            Optional[pd.DataFrame]: DataFrame containing top performing companies.
        """
        ...
    
    @property
    def top_growth_companies(self) -> Optional[_pd.DataFrame]:
        """
        Returns the top growth companies in the industry.
        
        Returns:
            Optional[pd.DataFrame]: DataFrame containing top growth companies.
        """
        ...
    


