"""
This type stub file was generated by pyright.
"""

from enum import Enum

class MarketRegion(str, Enum):
    """Market regions accepted by Yahoo's ``quote/marketSummary`` endpoint.

    Members are plain strings, so ``MarketRegion.EUROPE == "EUROPE"`` and
    ``Market("EUROPE")`` continues to work. Pass an enum member for IDE
    autocomplete and static checking: ``Market(MarketRegion.EUROPE)``.
    """
    US = ...
    GB = ...
    ASIA = ...
    EUROPE = ...
    RATES = ...
    COMMODITIES = ...
    CURRENCIES = ...
    CRYPTOCURRENCIES = ...


class Market:
    def __init__(self, market, session=..., timeout=...) -> None:
        ...
    
    @property
    def status(self): # -> Any | dict[Any, Any] | None:
        ...
    
    @property
    def summary(self): # -> Any | dict[Any, Any] | None:
        ...
    


