"""
This type stub file was generated by pyright.
"""

import pandas as _pd
from typing import Dict
from ..const import SECTOR_INDUSTY_MAPPING_LC
from ..utils import dynamic_docstring, generate_list_table_from_dict
from .domain import Domain

class Sector(Domain):
    """
    Represents a financial market sector and allows retrieval of sector-related data 
    such as top ETFs, top mutual funds, and industry data.
    """
    def __init__(self, key, session=..., region: str = ...) -> None:
        """
        Args:
            key (str): The key representing the sector.
            session (requests.Session, optional): A session for making requests. Defaults to None.
            region (str): Yahoo region (ISO 3166-1 alpha-2 country code, e.g.
                "US", "GB", "FR", "DE", "JP"). Scopes ``top_companies``,
                ``top_etfs`` and ``top_mutual_funds``. Defaults to "US".

        .. seealso::

            :attr:`Sector.industries <yfinance.Sector.industries>`
                Map of sector and industry
        """
        ...
    
    def __repr__(self): # -> str:
        """
        Returns the string representation of the Sector object.

        Returns:
            str: A string representation of the object.
        """
        ...
    
    @property
    def top_etfs(self) -> Dict[str, str]:
        """
        Gets the top ETFs for the sector.

        Returns:
            Dict[str, str]: A dictionary of ETF symbols and names.
        """
        ...
    
    @property
    def top_mutual_funds(self) -> Dict[str, str]:
        """
        Gets the top mutual funds for the sector.

        Returns:
            Dict[str, str]: A dictionary of mutual fund symbols and names.
        """
        ...
    
    @dynamic_docstring({ "sector_industry": generate_list_table_from_dict(SECTOR_INDUSTY_MAPPING_LC, bullets=True) })
    @property
    def industries(self) -> _pd.DataFrame:
        """
        Gets the industries within the sector.

        Returns:
            pandas.DataFrame: A DataFrame with industries' key, name, symbol, and market weight.

        {sector_industry}
        """
        ...
    


