"""
This type stub file was generated by pyright.
"""

import pandas as pd
from yfinance.data import YfData

class Analysis:
    def __init__(self, data: YfData, symbol: str) -> None:
        ...
    
    @property
    def earnings_estimate(self) -> pd.DataFrame:
        ...
    
    @property
    def revenue_estimate(self) -> pd.DataFrame:
        ...
    
    @property
    def eps_trend(self) -> pd.DataFrame:
        ...
    
    @property
    def eps_revisions(self) -> pd.DataFrame:
        ...
    
    @property
    def analyst_price_targets(self) -> dict:
        ...
    
    @property
    def earnings_history(self) -> pd.DataFrame:
        ...
    
    @property
    def growth_estimates(self) -> pd.DataFrame:
        ...
    


