"""
This type stub file was generated by pyright.
"""

import pandas as pd
from yfinance.data import YfData

class Fundamentals:
    def __init__(self, data: YfData, symbol: str) -> None:
        ...
    
    @property
    def financials(self) -> Financials:
        ...
    
    @property
    def earnings(self) -> dict:
        ...
    
    @property
    def shares(self) -> pd.DataFrame:
        ...
    


class Financials:
    def __init__(self, data: YfData, symbol: str) -> None:
        ...
    
    def get_income_time_series(self, freq=...) -> pd.DataFrame:
        ...
    
    def get_balance_sheet_time_series(self, freq=...) -> pd.DataFrame:
        ...
    
    def get_cash_flow_time_series(self, freq=...) -> pd.DataFrame:
        ...
    
    _CHUNK_KEYS = ...


