"""
This type stub file was generated by pyright.
"""

import pandas as pd
from collections.abc import Mapping
from yfinance import utils

_CURRENCY_CONVERSIONS = ...
class HistoryMetadata(Mapping):
    """
    Dict-like lazy wrapper for PriceHistory metadata.

    Yahoo only returns ``tradingPeriods`` for intraday chart requests.  Most
    metadata is available from the normal/base history fetch, so defer the
    intraday metadata fetch until callers actually request ``tradingPeriods``.
    """
    _LAZY_KEYS = ...
    _LAZY_VALUE = ...
    def __init__(self, price_history) -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __iter__(self): # -> Iterator[Any]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def keys(self): # -> list[Any]:
        ...
    
    def items(self): # -> list[tuple[Any, Any]]:
        ...
    
    def values(self): # -> list[Any]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class PriceHistory:
    def __init__(self, data, ticker, tz, session=...) -> None:
        ...
    
    @utils.log_indent_decorator
    def history(self, period=..., interval=..., start=..., end=..., prepost=..., actions=..., auto_adjust=..., back_adjust=..., repair=..., keepna=..., rounding=..., timeout=..., raise_errors=...) -> pd.DataFrame:
        """
        :Parameters:
            period : str
              | Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
              | Default: '1mo' if start & end None
              | Can combine with start/end e.g. end = start + period
            interval : str
              | Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
              | Intraday data cannot extend last 60 days
              | Note: 30m data is fetched from Yahoo as 15m then resampled, to work around a Yahoo API bug
            start : str
              | Download start date string (YYYY-MM-DD) or _datetime, inclusive.
              | Default: 99 years ago
              | E.g. for start="2020-01-01", first data point = "2020-01-01"
            end : str
              | Download end date string (YYYY-MM-DD) or _datetime, exclusive.
              | Default: now
              | E.g. for end="2023-01-01", last data point = "2022-12-31"
            prepost : bool
              | Include Pre and Post market data in results?
              | Default: False
            auto_adjust : bool
              | Adjust all OHLC automatically?
              | Default: True
            back_adjust : bool
              | Back-adjusted data to mimic true historical prices
            repair : bool
              | Fixes price errors in Yahoo data: 100x, missing, bad dividend adjust.
              | Default: False
              | Full details at: :doc:`../advanced/price_repair`.
            keepna : bool
              | Keep NaN rows returned by Yahoo?
              | Default: False
            rounding : bool
              | Optional: Round values to 2 decimal places?
              | Default: False = use precision suggested by Yahoo!
            timeout : None or float
              | Optional: timeout fetches after N seconds
              | Default: 10 seconds
            raise_errors : bool
                If True, then raise errors as Exceptions instead of logging.
        """
        ...
    
    def get_history_metadata(self, repair=...) -> dict:
        """
        repair default value depends on whether user requested price repair
        with previous history() call. If user did not set repair here, then
        it is set to match previous history() call.
        """
        ...
    
    def get_dividends(self, period=..., repair=...) -> pd.Series:
        ...
    
    def get_capital_gains(self, period=..., repair=...) -> pd.Series:
        ...
    
    def get_splits(self, period=..., repair=...) -> pd.Series:
        ...
    
    def get_actions(self, period=...) -> pd.Series:
        ...
    


