"""
This type stub file was generated by pyright.
"""

import pandas as pd
from yfinance.data import YfData

_QUOTE_SUMMARY_URL_ = ...
class Holders:
    _SCRAPE_URL_ = ...
    def __init__(self, data: YfData, symbol: str) -> None:
        ...
    
    @property
    def major(self) -> pd.DataFrame:
        ...
    
    @property
    def institutional(self) -> pd.DataFrame:
        ...
    
    @property
    def mutualfund(self) -> pd.DataFrame:
        ...
    
    @property
    def insider_transactions(self) -> pd.DataFrame:
        ...
    
    @property
    def insider_purchases(self) -> pd.DataFrame:
        ...
    
    @property
    def insider_roster(self) -> pd.DataFrame:
        ...
    


