"""
This type stub file was generated by pyright.
"""

import pandas as pd
from yfinance.data import YfData

info_retired_keys_price = ...
info_retired_keys_exchange = ...
info_retired_keys_marketCap = ...
info_retired_keys_symbol = ...
_VALUATION_MEASURE_LABELS = ...
_VALUATION_FREQ_PREFIX = ...
info_retired_keys = ...
_QUOTE_SUMMARY_URL_ = ...
class FastInfo:
    def __init__(self, tickerBaseObject) -> None:
        ...
    
    def keys(self): # -> list[str]:
        ...
    
    def items(self): # -> list[tuple[str, Any]]:
        ...
    
    def values(self): # -> list[Any]:
        ...
    
    def get(self, key, default=...): # -> Any | None:
        ...
    
    def __getitem__(self, k): # -> Any:
        ...
    
    def __contains__(self, k): # -> bool:
        ...
    
    def __iter__(self): # -> Iterator[str]:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def toJSON(self, indent=...): # -> str:
        ...
    
    @property
    def currency(self):
        ...
    
    @property
    def quote_type(self):
        ...
    
    @property
    def exchange(self):
        ...
    
    @property
    def timezone(self):
        ...
    
    @property
    def shares(self): # -> int | None:
        ...
    
    @property
    def last_price(self): # -> float | None:
        ...
    
    @property
    def previous_close(self): # -> float | None:
        ...
    
    @property
    def regular_market_previous_close(self): # -> float | None:
        ...
    
    @property
    def open(self): # -> float | None:
        ...
    
    @property
    def day_high(self): # -> float | None:
        ...
    
    @property
    def day_low(self): # -> float | None:
        ...
    
    @property
    def last_volume(self): # -> int | None:
        ...
    
    @property
    def fifty_day_average(self): # -> float | None:
        ...
    
    @property
    def two_hundred_day_average(self): # -> float | None:
        ...
    
    @property
    def ten_day_average_volume(self): # -> int | None:
        ...
    
    @property
    def three_month_average_volume(self): # -> int | None:
        ...
    
    @property
    def year_high(self): # -> float:
        ...
    
    @property
    def year_low(self): # -> float:
        ...
    
    @property
    def year_change(self): # -> float | None:
        ...
    
    @property
    def market_cap(self): # -> float | None:
        ...
    


class Quote:
    def __init__(self, data: YfData, symbol: str) -> None:
        ...
    
    @property
    def info(self) -> dict:
        ...
    
    @property
    def sustainability(self) -> pd.DataFrame:
        ...
    
    @property
    def recommendations(self) -> pd.DataFrame:
        ...
    
    @property
    def upgrades_downgrades(self) -> pd.DataFrame:
        ...
    
    @property
    def calendar(self) -> dict:
        ...
    
    @property
    def sec_filings(self) -> dict:
        ...
    
    @property
    def valuation_measures(self) -> pd.DataFrame:
        ...
    
    def get_valuation_measures(self, freq=..., periods=...) -> pd.DataFrame:
        """Valuation measures (market cap, P/E, P/S, P/B, EV/EBITDA, ...).

        Returns a DataFrame with the 9 valuation measures as rows and a
        ``Current`` column plus period-end date columns (newest first). Values
        are raw numeric measures (floats, with ``NaN`` for missing cells); the
        date column labels remain ``"M/D/YYYY"`` strings.

        Args:
            freq: period columns to return — "quarterly" (default), "monthly",
                "yearly" or "trailing". The "Current" column always reflects the
                latest trailing value.
            periods: cap on the number of period (date) columns returned, newest
                first. Must be an int >= 0 or None. The default of 5 matches the
                column count the old key-statistics page showed. ``periods=0``
                returns only the "Current" column (a 9x1 DataFrame); ``None``
                (or a value larger than the available history) returns every
                available period column. The ``valuation`` property uses this
                default — call the method form to control ``periods``.

        Returns:
            pd.DataFrame: valuation measures, ``Current`` first, sliced to at
                most ``periods`` period columns.
        """
        ...
    
    @staticmethod
    def valid_modules(): # -> tuple[Literal['summaryProfile'], Literal['summaryDetail'], Literal['assetProfile'], Literal['fundProfile'], Literal['price'], Literal['quoteType'], Literal['esgScores'], Literal['incomeStatementHistory'], Literal['incomeStatementHistoryQuarterly'], Literal['balanceSheetHistory'], Literal['balanceSheetHistoryQuarterly'], Literal['cashFlowStatementHistory'], Literal['cashFlowStatementHistoryQuarterly'], Literal['defaultKeyStatistics'], Literal['financialData'], Literal['calendarEvents'], Literal['secFilings'], Literal['upgradeDowngradeHistory'], Literal['institutionOwnership'], Literal['fundOwnership'], Literal['majorDirectHolders'], Literal['majorHoldersBreakdown'], Literal['insiderTransactions'], Literal['insiderHolders'], Literal['netSharePurchaseActivity'], Literal['earnings'], Literal['earningsHistory'], Literal['earningsTrend'], Literal['industryTrend'], Literal['indexTrend'], Literal['sectorTrend'], Literal['recommendationTrend'], Literal['futuresChain']]:
        ...
    


