"""
This type stub file was generated by pyright.
"""

import numbers
from abc import ABC, abstractmethod
from typing import Dict, List, Literal, TypeVar, Union
from yfinance.const import EQUITY_SCREENER_EQ_MAP, EQUITY_SCREENER_FIELDS, ETF_SCREENER_EQ_MAP, ETF_SCREENER_FIELDS, FUND_SCREENER_EQ_MAP, FUND_SCREENER_FIELDS
from ..utils import dynamic_docstring, generate_list_table_from_dict_universal

T = TypeVar('T', bound=Union[str, numbers.Real])
Operator = Literal['eq', 'is-in', 'btwn', 'gt', 'lt', 'gte', 'lte', 'and', 'or']
class QueryBase(ABC):
    def __init__(self, operator: Operator, operand: Union[List[QueryBase], List[str], List[numbers.Real]]) -> None:
        ...
    
    @property
    @abstractmethod
    def valid_fields(self) -> Dict:
        ...
    
    @property
    @abstractmethod
    def valid_values(self) -> Dict:
        ...
    
    def to_dict(self) -> Dict:
        ...
    
    def __repr__(self, indent=...) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class EquityQuery(QueryBase):
    """
    The `EquityQuery` class constructs filters for stocks based on specific criteria such as region, sector, exchange, and peer group.

    Start with value operations: `EQ` (equals), `IS-IN` (is in), `BTWN` (between), `GT` (greater than), `LT` (less than), `GTE` (greater or equal), `LTE` (less or equal).

    Combine them with logical operations: `AND`, `OR`.

    Example:
        Predefined Yahoo query `aggressive_small_caps`:
        
        .. code-block:: python

            from yfinance import EquityQuery

            EquityQuery('and', [
                EquityQuery('is-in', ['exchange', 'NMS', 'NYQ']), 
                EquityQuery('lt', ["epsgrowth.lasttwelvemonths", 15])
            ])
    """
    @dynamic_docstring({ "valid_operand_fields_table": generate_list_table_from_dict_universal(EQUITY_SCREENER_FIELDS) })
    @property
    def valid_fields(self) -> Dict:
        """
        Valid operands, grouped by category.
        {valid_operand_fields_table}
        """
        ...
    
    @dynamic_docstring({ "valid_values_table": generate_list_table_from_dict_universal(EQUITY_SCREENER_EQ_MAP, concat_keys=['exchange', 'industry']) })
    @property
    def valid_values(self) -> Dict:
        """
        Most operands take number values, but some have a restricted set of valid values.
        {valid_values_table}
        """
        ...
    


class FundQuery(QueryBase):
    """
    The `FundQuery` class constructs filters for mutual funds based on specific criteria such as region, sector, exchange, and peer group.

    Start with value operations: `EQ` (equals), `IS-IN` (is in), `BTWN` (between), `GT` (greater than), `LT` (less than), `GTE` (greater or equal), `LTE` (less or equal).

    Combine them with logical operations: `AND`, `OR`.

    Example:
        Predefined Yahoo query `solid_large_growth_funds`:
        
        .. code-block:: python

            from yfinance import FundQuery
            
            FundQuery('and', [
                FundQuery('eq', ['categoryname', 'Large Growth']), 
                FundQuery('is-in', ['performanceratingoverall', 4, 5]), 
                FundQuery('lt', ['initialinvestment', 100001]), 
                FundQuery('lt', ['annualreturnnavy1categoryrank', 50]), 
                FundQuery('eq', ['exchange', 'NAS'])
            ])
    """
    @dynamic_docstring({ "valid_operand_fields_table": generate_list_table_from_dict_universal(FUND_SCREENER_FIELDS) })
    @property
    def valid_fields(self) -> Dict:
        """
        Valid operands, grouped by category.
        {valid_operand_fields_table}
        """
        ...
    
    @dynamic_docstring({ "valid_values_table": generate_list_table_from_dict_universal(FUND_SCREENER_EQ_MAP) })
    @property
    def valid_values(self) -> Dict:
        """
        Most operands take number values, but some have a restricted set of valid values.
        {valid_values_table}
        """
        ...
    


class ETFQuery(QueryBase):
    """
    The `ETFQuery` class constructs filters for ETFs based on specific criteria such as category, fund family, exchange, and performance ratings.

    Start with value operations: `EQ` (equals), `IS-IN` (is in), `BTWN` (between), `GT` (greater than), `LT` (less than), `GTE` (greater or equal), `LTE` (less or equal).

    Combine them with logical operations: `AND`, `OR`.

    Example:
        Predefined Yahoo query `top_etfs_us`:
        
        .. code-block:: python

            from yfinance import ETFQuery

            ETFQuery('and', [
                ETFQuery('gt', ['intradayprice', 10]),
                ETFQuery('is-in', ['performanceratingoverall', 4, 5]),
                ETFQuery('eq', ['region', 'us'])
            ])
    """
    @dynamic_docstring({ "valid_operand_fields_table": generate_list_table_from_dict_universal(ETF_SCREENER_FIELDS) })
    @property
    def valid_fields(self) -> Dict:
        """
        Valid operands, grouped by category.
        {valid_operand_fields_table}
        """
        ...
    
    @dynamic_docstring({ "valid_values_table": generate_list_table_from_dict_universal(ETF_SCREENER_EQ_MAP) })
    @property
    def valid_values(self) -> Dict:
        """
        Most operands take number values, but some have a restricted set of valid values.
        {valid_values_table}
        """
        ...
    


